spring:
  profiles:
    active: ${PROFILE_ACTIVE:default}
  application:
    name: news-letter-ai
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JSM_EMAIL}
    password: ${JSM_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.lucasmoraist: ${LOG_LEVEL}

secrets:
  google:
    genai:
      api-key: ${SECRETS_GOOGLE_GENAI_API_KEY}

app:
  security-ignore:
    actuatorHealth: /actuator/health
    actuatorLiveness: /actuator/health/liveness
    actuatorReadiness: /actuator/health/readiness
    customerSave: /api/v1/customer/save
  allowed-origins:
    - http://localhost:3000