spring:
  profiles:
    active: ${PROFILE_ACTIVE:default}
  application:
    name: news-letter-ai

logging:
  level:
    com.lucasmoraist: ${LOG_LEVEL:DEBUG}

secrets:
  brevo:
    sender-email: ${JSM_EMAIL}
    api-url: https://api.brevo.com/v3
    api-key: ${SECRETS_BREVO_API_KEY}
  google:
    genai:
      api-key: ${SECRETS_GOOGLE_GENAI_API_KEY}

app:
  security-ignore:
    actuatorHealth: /actuator/health
    actuatorLiveness: /actuator/health/liveness
    actuatorReadiness: /actuator/health/readiness
    customerSave: /api/v1/customer/save
    registerView: /register
    registerViewDefault: /