spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
